### ISSUE TITLE
Remaining slow cube/interface animations in v1.8.2pb1

### ISSUE THREAD

**Issue by akaine** [Nielk1/DarkReignLauncher#2]
v1.8.2pb1 build still contains at least 2 cube/interface animations that remain slow:
- Main screen <-> Faction Mission (when you click on a faction icon directly from the main screen)
- Faction Mission opening (the brownish shroud clearing the faction specific mission objectives screen, the one with the "Launch" mission button)

Please see the video for more detail: https://drive.google.com/file/d/1WL7kV2wV2XfzuWkMM2h3BMs0fWXrm3f_/view?usp=sharing

**Comment by Nielk1** [comment]
videos regenerated to resolve missing videos and fix some sound chirping in some cases
